#Typical yml file for CONNECTOR-SERVICE
version: 0.0
os: linux
files:
  - source: /
    destination: /apps/webapp-service/
permissions:
  - object: .
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/deploy_service.sh
      timeout: 400
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 60
      runas: root
